iter13
ZhuzhomaAL/go-shortener pull request #13
Opened 2023-07-18 15:46 UTC by ZhuzhomaAL

2023-07-20 13:48 UTC, valentinsoe requested changes
Спасибо за работу.
Смерджи пожалуйста 9 итерацию сначала, а то мне приходится смотреть гораздо больший по объему diff чем хотелось бы.

2023-07-20 14:28 UTC, valentinsoe requested changes
Спасибо за работу.
В целом все будет работать.
Что бы хотелось видеть - разделение кода на чуть большее количество модулей.
Хотя бы разделить часть связанную с обработкой запросов(хендлеры) и хранилище.
Еще было бы неплохо сделать интерфейс для хранилища и разные его реализации. Одну из них инциализировать в зависимости от конфигурации и передавать в обработчики. А обработчики далее могли бы работать с этими реализациями единообразно.

Я в целом готов принять работу. С точки зрения того, что все задачи она решает. Но хотелось бы навести немного красоты с точки зрения организации кода.

2023-07-20 14:28 UTC, valentinsoe commented on internal/app/handlers.go
>  	resp, err := io.ReadAll(req.Body)
Занудство. resp - не самое удачное имя для переменной в которой request.Body.

2023-07-20 14:28 UTC, valentinsoe commented on cmd/shortener/main.go
> +	if db != nil {
Если мы не сможем инициализировать таблицу и индекс, то продолжать работать нашему сервису не имеет смысл.
А коннекшен к базе в которой нет ни таблицы, ни индекса мы уже передали в роутер:)
Предлагаю инициализацию БД(проверку коннекта, создание всех нужных объектов) собрать в одном месте.

2023-07-20 14:28 UTC, valentinsoe commented on internal/app/handlers.go
> +				a.log.L.Error("failed to persist data", zap.Error(err))
Занудство - текст в логе кажется весьма неоднозначно определяет проблему.

2023-07-20 14:28 UTC, valentinsoe commented on internal/app/handlers.go
> +	err := a.db.Ping()
Что произойдет, если db будет равен nil?

2023-07-20 14:28 UTC, valentinsoe commented on internal/app/store.go
> +		inserts = append(inserts, fmt.Sprintf("($%d, $%d)", i+1, i+2))
Такой подход имеет место быть:)
Но важно понимать, что он очень ограничен. Если размер batch будет достаточно большой(больше 32767 строк), то это не сработает.
Исправлять это не обязательно, но одним из подходов будет открыть транзакцию и вызывать отдельные запросы). А другим - использовать специфичные для БД функции batch-загрузки:)

2023-07-20 14:28 UTC, valentinsoe commented on internal/app/store.go
> +	_, err = res.RowsAffected()
Это лишнее. Если мы не пытаемся использовать количество "измененных" строк, то и получать их не нужно.

2023-07-22 17:20 UTC, ZhuzhomaAL commented
>

2023-07-22 17:21 UTC, ZhuzhomaAL commented
> Спасибо за работу. В целом все будет работать. Что бы хотелось видеть - разделение кода на чуть большее количество модулей. Хотя бы разделить часть связанную с обработкой запросов(хендлеры) и хранилище. Еще было бы неплохо сделать интерфейс для хранилища и разные его реализации. Одну из них инциализировать в зависимости от конфигурации и передавать в обработчики. А обработчики далее могли бы работать с этими реализациями единообразно.
> 
> Я в целом готов принять работу. С точки зрения того, что все задачи она решает. Но хотелось бы навести немного красоты с точки зрения организации кода.

Оставила в app только то, что связано с хендлерами

2023-07-22 17:22 UTC, ZhuzhomaAL commented on internal/app/handlers.go
> +				a.log.L.Error("failed to persist data", zap.Error(err))
Вот тут не очень поняла, что лучше написать. Вроде бы это ошибка сохранения

2023-07-22 17:24 UTC, ZhuzhomaAL commented on internal/app/store.go
> +		inserts = append(inserts, fmt.Sprintf("($%d, $%d)", i+1, i+2))
xXПеределала на использование чанков по 1000 объектов

2023-07-25 17:38 UTC, valentinsoe commented on internal/app/handlers.go
> +				a.log.L.Error("failed to persist data", zap.Error(err))
Ну можно более подробно написать, что мы столкнулись с duplicate key, а после этого не смогли получить короткую ссылку из длинной.

2023-07-25 17:40 UTC, valentinsoe approved these changes
Спасибо за исправления.
Я бы попросил на будущее делить код еще чуть на более мелкие функции(например вынести чтение конига в отдельную функцию).

2023-08-01 14:20 UTC, merged