iter5
ZhuzhomaAL/go-shortener pull request #5
Opened 2023-05-09 21:23 UTC by ZhuzhomaAL

2023-05-11 12:19 UTC, s-shpak requested changes

2023-05-11 12:19 UTC, s-shpak commented on go.sum
`go.sum` необходимо обновить с помощью `go mod tidy`

2023-05-11 12:19 UTC, s-shpak commented on go.mod
> +go 1.18
Используй лучше последнюю версию `1.20`

2023-05-11 12:19 UTC, s-shpak commented on cmd/shortener/main.go
> +		panic(err)
Не стоит паниковать, используй лучше `log.Fatal`

2023-05-11 12:19 UTC, s-shpak commented on cmd/shortener/main.go
> +	fmt.Println("Running server on", config.FlagRunAddr)
Сообщения для логгирования событий лучше выводить с помощью логера, на данном этапе достаточно стандартного, из пакета `log`

2023-05-11 12:19 UTC, s-shpak commented on cmd/config/config.go
> +	FlagRunAddr   string
Старайся не использовать глобальные переменные, подумай, как можно обойтись без них

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers.go
> +	if req.Method != http.MethodPost {
Эта проверка лишняя, роутер делает ее за нас

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers.go
> +	if len(resp) == 0 {
Сначала стоит проверить ошибку: в Go если ошибка ненулевая, то использовать основное возвращенное значение, как правило, нельзя

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers.go
> +	urlList[genShortStr] = string(resp)
Что произойдет, если мы одновременно попытаемся записать и прочитать данные из `urlList` ? Как этого избежать?

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers.go
> +	respString := fmt.Sprintf(config.FlagShortAddr+"/%s", genShortStr)
Т.к. это URL, используй лучше https://pkg.go.dev/net/url#JoinPath

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers.go
> +	_, err = rw.Write([]byte(respString))
Эту ошибку можно обернуть в `if`, чтобы не переписывать переменную `err`, определенную в области видимости функции

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers.go
> +	if req.Method != http.MethodGet {
См. комментарий выше

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers.go
> +	id := chi.URLParam(req, "id")
Мне не очень нравится то, что ты используешь функциональность роутера здесь: представь, что завтра мы поменяем `chi` на `httprouter` - это приведет к тому, что эта функция сломается, хотя так быть, вобщем-то, не должно. Как можно этого избежать?

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers.go
> +	_, err := rw.Write([]byte(location))
См. комментарий выше

2023-05-11 12:19 UTC, s-shpak commented on internal/app/handlers_test.go
Молодец, хорошее тестовое покрытие!

2023-05-17 16:32 UTC, ZhuzhomaAL commented on internal/app/handlers.go
> +	urlList[genShortStr] = string(resp)
переделала на sync.Map

2023-05-17 16:40 UTC, ZhuzhomaAL commented on internal/app/handlers.go
> +	id := chi.URLParam(req, "id")
вроде бы пока роутер  используется только тут и если убрать получение параметра, то смысла вообще не будет. 
p.s. плюс мистер course author в тредике сказал "не заморачиваться"

2023-05-17 16:41 UTC, ZhuzhomaAL commented on internal/app/handlers_test.go
спасибо, я как раз тестировщик)

2023-05-19 10:55 UTC, s-shpak commented on internal/app/handlers.go
> +	id := chi.URLParam(req, "id")
Ну, если господин автор сказал, то ладно :) Можем обсудить на 1-1 потом, если захочешь

2023-05-19 10:58 UTC, s-shpak requested changes

2023-05-19 10:58 UTC, s-shpak commented on internal/app/handlers_test.go
> +		t.Run(
Я рекоммендую привыкнуть переопределять переменные из цикла внутри этого цикла для тестов (в данном случае `tt := tt`). Это особенно важно для тестов, т.к. тесты часто запускаются параллельно, а в этом случае возможны проблемы: https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/

2023-05-19 10:58 UTC, s-shpak commented on internal/app/handlers.go
> +	if _, err := rw.Write([]byte(respString)); err != nil {
Здесь ошибку можно залогировать

2023-05-19 11:00 UTC, s-shpak commented on internal/app/handlers.go
> +	urlList[genShortStr] = string(resp)
Пока пойдет, в дальнейшем надо будет переписать на мьютексах. Если хочешь, то на 1-1 могу объяснить, почему `sync.Map` используется в продакшене не часто

2023-05-19 15:45 UTC, s-shpak approved these changes

2023-05-23 18:13 UTC, merged