iter9
ZhuzhomaAL/go-shortener pull request #9
Opened 2023-06-01 22:54 UTC by ZhuzhomaAL

2023-06-01 23:14 UTC, ZhuzhomaAL commented on internal/app/tmp/short-url-db.json
> +{"id":"17fbb137-073d-43cc-b386-0c695abcdbe3","short_url":"BR76Q4Jo","original_url":"https://practicum.yandex.ru"}
без этой папки падают автотесты, не смогла побороть

2023-06-04 12:12 UTC, s-shpak requested changes

2023-06-04 12:12 UTC, s-shpak commented on cmd/shortener/main.go
> +	if err := l.Initialize(appConfig.FlagLogLevel); err != nil {
Не стоит инициалзировтаь логгер так, возвращай объект прямо из констркутора

2023-06-04 12:12 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, err.Error(), http.StatusBadRequest)
Эта ошибка внутренняя, ее не стоит отдавать пользователю (как и другие внутренние ошибки). А вот залогировать ее стоит

2023-06-04 12:12 UTC, s-shpak commented on internal/app/handlers.go
> +		log.Println(err)
Ошибки из сторонних библиотек или пакетов нужно оборачивать

2023-06-04 12:12 UTC, s-shpak commented on internal/app/handlers_router.go
> +	fWriter, _ := NewFileWriter(appConfig.FlagStorage)
Ошибки надо проверять

2023-06-04 12:12 UTC, s-shpak commented on internal/app/handlers_router.go
> +				log.Fatalln(err)
Не надо выходить из программы из глубины кода - пробрось эту ошибку наверх

2023-06-04 12:12 UTC, s-shpak commented on internal/app/tmp/short-url-db.json
> +{"id":"17fbb137-073d-43cc-b386-0c695abcdbe3","short_url":"BR76Q4Jo","original_url":"https://practicum.yandex.ru"}
А если папку создавать при старте программы? См. https://pkg.go.dev/os#MkdirAll

2023-06-04 12:12 UTC, s-shpak commented on internal/logger/logger.go
> +			start := time.Now()
Таймер лучше стартовать перед вызовом хендлера

2023-06-04 12:12 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, "failed to persist data", http.StatusInternalServerError)
См. комментарий про неожиданные ошибки

2023-06-04 12:12 UTC, s-shpak commented on tmp/short-url-db.json
Это не должно быть в репозитории

2023-06-07 17:50 UTC, ZhuzhomaAL commented on internal/app/handlers.go
> +		log.Println(err)
тут я не очень поняла, что значит оборачивать. добавила вывод ошибки

2023-06-07 18:41 UTC, ZhuzhomaAL commented on internal/app/handlers.go
> +		http.Error(rw, err.Error(), http.StatusBadRequest)
я тут сделала пайнэплэплпэн с ошибкой выше, не знаю насколько это правильно

2023-06-07 18:43 UTC, ZhuzhomaAL commented on internal/app/handlers.go
> +		http.Error(rw, "failed to persist data", http.StatusInternalServerError)
это какой?

2023-06-08 11:24 UTC, s-shpak requested changes

2023-06-08 11:24 UTC, s-shpak commented on cmd/config/config.go
> +	flag.StringVar(&appConfig.FlagStorage, "f", "tmp/short-url-db.json", "json file address")
На самом деле по умолчанию предполагается, что файл пишется во временную директорию Linux: `/tmp` (а не в локальную директорию `tmp`)

2023-06-08 11:24 UTC, s-shpak commented on cmd/shortener/main.go
> +		log.Fatal(err)
Идея создания отделной функции `run` заключается в том, что мы возвращаем из нее ошибку, а `log.Fatal` ввызываем в `main` только один раз, если эта ошибка не `nil`

2023-06-08 11:24 UTC, s-shpak commented on cmd/shortener/main.go
> +	err = os.MkdirAll("tmp", 0750)
В принципе, при использовании `/tmp` по умолчанию можно не создавать папку при старте программы, а просто возвращать ошибку, если папки не существует. Тем более не надо каждый раз создавать `tmp`: а что если пользователь хочет сохранить файл по другому адресу?

Я бы посоветовал просто убрать эту логику. Но если ты хочешь ее оставить, то надо распарсить путь к файлу для сохранения записей и создавать папку из этого пути.

2023-06-08 11:24 UTC, s-shpak commented on internal/app/file.go
> +func (w *Writer) WriteFile(file *URL) error {
Параметр лучше переименовать

2023-06-08 11:24 UTC, s-shpak commented on internal/app/gzip.go
> +	c.w.Header().Set("Content-Encoding", "gzip")
Лучше проверить, что `statusCode` не ошибочный: в случае ошибки контент не сжимается

2023-06-08 11:24 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, "failed to persist data", http.StatusInternalServerError)
В случае внутренней, неожиданной ошибке на сервере (`InternalServerError`) пользоавтелю не надо отдавать причину ее возникновения: это опасно с т.з. безопасности приложения. Стоит залогировать эту ошибку (т.е. надо прокинуть логгер из main сюда) и отдать пользователю сообщение типа `internal server error occurred`

2023-06-08 11:24 UTC, s-shpak commented on internal/app/handlers.go
> +		} else {
`else` здесь не нужен: старайся делать код более плоским

2023-06-08 11:24 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, "failed to persist data", http.StatusInternalServerError)
[Эта ошибка внутренняя, ее не стоит отдавать пользователю (как и другие внутренние ошибки). А вот залогировать ее стоит](https://github.com/ZhuzhomaAL/go-shortener/pull/9#discussion_r1216624591)

2023-06-08 11:24 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, "failed to process request", http.StatusInternalServerError)
См выше

2023-06-08 11:24 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, "failed to retrieve response", http.StatusInternalServerError)
См выше

2023-06-08 11:24 UTC, s-shpak commented on internal/logger/logger.go
> +type MyLogger struct {
Я бы не стал оборачивать логгер в свою структуру, используй его лучше напрямую

2023-06-08 11:24 UTC, s-shpak commented on internal/app/handlers_router.go
> +			} else {
Плоский код > неплоский код

2023-06-08 11:24 UTC, s-shpak commented on internal/app/handlers.go
> +	respString, err := url.JoinPath(a.appConfig.FlagShortAddr, genShortStr)
Это больше похоже на внутреннюю ошибку

2023-06-08 11:24 UTC, s-shpak commented on internal/app/handlers.go
> +	err = a.fWriter.WriteFile(fileURL)
А как обрабатывается ситуация, когда пользователь отключает запись файла, т.е. когда передает пустой путь к файлу?

Кроме того я бы добавил логику записи файла в storage, но это "задание со звездочкой", если хочешь, то можем обсудить на следующем 1-1, сейчас это имплеменить не обязательно

2023-06-08 16:48 UTC, ZhuzhomaAL commented on internal/logger/logger.go
> +type MyLogger struct {
а как тогда быть с методом RequestLogger, который привязан к структуре?

2023-06-08 16:51 UTC, ZhuzhomaAL commented on cmd/config/config.go
> +	flag.StringVar(&appConfig.FlagStorage, "f", "tmp/short-url-db.json", "json file address")
у меня винда, без /tmp не запускается

2023-06-08 16:51 UTC, ZhuzhomaAL commented on cmd/shortener/main.go
> +	err = os.MkdirAll("tmp", 0750)
убрала

2023-06-08 17:14 UTC, ZhuzhomaAL commented on internal/app/handlers_router.go
> +			} else {
а как сделать, чтобы и ошибку вернуть и чтобы программа не переставала работать, когда EOF?

2023-06-08 17:15 UTC, ZhuzhomaAL commented on internal/app/handlers.go
> +	err = a.fWriter.WriteFile(fileURL)
лучше обсудить

2023-06-08 17:40 UTC, ZhuzhomaAL commented on internal/app/gzip.go
> +	c.w.Header().Set("Content-Encoding", "gzip")
добавила if statusCode < 300 {
		c.w.Header().Set("Content-Encoding", "gzip")
	} 
и негативные тесты начали падать, как будто ответ кодируется
\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xff\xca\xc9ON,\xc9\xcc\xcfS\xc8\xcb/QH\xcb/\xcdK\xe1\x02\x04\x00\x00\xff\xff>\xee\b\xa6\x13\x00\x00\x00" does not contain "location not found"
дебагом не смогла раскопать, почему

2023-06-08 23:15 UTC, s-shpak commented on internal/app/handlers.go
> +		if err == io.EOF {
а что если `err != io.EOF` ?

2023-06-08 23:15 UTC, s-shpak commented on internal/app/handlers.go
> +	var result result
Кстати, в Go принято объявлять переменные рядом с местом их использования

2023-06-08 23:15 UTC, s-shpak commented on internal/app/handlers.go
> +		a.log.L.Error("failed to process request")
Оригинальные ошибки тоже стоит логировать

2023-06-08 23:15 UTC, s-shpak commented on internal/app/handlers_router.go
> +			} else {
`break` выходит из цикла `for`, потому можно просто убрать `else`:

```go
if err != nil {
    if err == io.EOF {
        break
    }
    return nil, fmt.Errorf("failed to read the storage file: %w", err)
}
```

2023-06-08 23:15 UTC, s-shpak commented on internal/logger/logger.go
> +type MyLogger struct {
Я бы разделил логгер и middleware: в main я бы возвращал логгер, а конструктор middleware (`MyLogger`, который лучше обозвать `LoggingMiddleware`, например), принимал бы логгер как параметр и использовал бы его

2023-06-08 23:15 UTC, s-shpak commented on internal/app/gzip.go
> +	c.w.Header().Set("Content-Encoding", "gzip")
My bad, он действительно сжимается

2023-06-08 23:15 UTC, s-shpak commented on internal/app/handlers.go
> +		log.Println(err)
"Оборачивать" в данном контексте = добавить к ошибке свое сообщение, чтобы, читая лог, было понятно, где эта ошибка возникла

2023-06-08 23:18 UTC, s-shpak commented on internal/app/handlers.go
> +	err = a.fWriter.WriteFile(fileURL)
Обсудить можно, но вторую часть. А обрабатывать ситуацию пустого пути к файлу надо в этом спринте (это в ТЗ): если путь к файлу пустой, то должен отрабатывать только `memoryStore`

2023-06-09 17:22 UTC, s-shpak requested changes

2023-06-09 17:22 UTC, s-shpak commented on internal/app/handlers.go
> +		a.log.L.Error(fmt.Sprintf("failed to process request: %s", err))
В zap есть лучшая возможность выводить ошибки

```go
a.log.L.Error("failed to process request", zap.Error(err))
```

2023-06-09 17:22 UTC, s-shpak commented on internal/app/handlers.go
> +		http.Error(rw, "internal server error occurred", http.StatusInternalServerError)
ошибку надо бы залогировать

2023-06-09 18:14 UTC, s-shpak approved these changes

2023-07-20 13:50 UTC, merged